apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: webhook
spec:
  template:
    serviceAccountName: operate-workflow-sa
  dependencies:
  - name: test-dep
    eventSourceName: webhook
    eventName: example
  triggers:
  - template:
      name: trigger
      argoWorkflow:
        group: argoproj.io
        version: v1alpha1
        resource: workflows
        operation: submit
        source:
          resource:
            apiVersion: argoproj.io/v1alpha1
            kind: Workflow
            metadata:
              generateName: argo-workflows-demo-
              namespace: argo-events
            spec:
              entrypoint: build
              serviceAccountName: operate-workflow-sa
              volumes:
              - name: regcred
                secret:
                  secretName: regcred
                  items:
                    - key: dockerconfig.json
                      path: config.json
              templates:
              - name: build
                dag:
                  tasks:
                  - name: build
                    templateRef:
                      name: container-image
                      template: build-kaniko-git
                      clusterScope: false
                    arguments:
                      parameters:
                      - name: app_repo
                        value: git://github.com/nekia/airtng-node.git
                      - name: container_image
                        value: nekia/my-airtng-node
                      - name: container_tag
                        value: "1.0.0"
