apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: webhook
spec:
  template:
    serviceAccountName: default
  dependencies:
    - name: test-dep
      eventSourceName: webhook
      eventName: example
  triggers:
    - template:
        name: webhook-workflow-trigger
        k8s:
          group: argoproj.io
          version: v1alpha1
          resource: workflows
          operation: create
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: Workflow
              metadata:
                generateName: webhook-
              spec:
                entrypoint: build
                volumes:
                - name: regcred
                  secret:
                    secretName: regcred
                    items:
                      - key: dockerconfig.json
                        path: config.json
                templates:
                  dag:
                    tasks:
                    - name: build
                      templateRef:
                        name: container-image
                        template: build-kaniko-git
                        clusterScope: true
                      arguments:
                        parameters:
                        - name: app_repo
                          value: git://github.com/nekia/airtng-node.git
                        - name: container_image
                          value: nekia/my-airtng-node
                        - name: container_tag
                          value: "1.0.0"
