apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - limit-resource.yaml
  - eventbus-native.yaml
  - sensor-rbac.yaml
  - workflow-rbac.yaml
  - argo-workflows-templates-build-kaniko-git.yaml
  - event-sources-github.yaml
  - event-sensors-github.yaml
