apiVersion: v1
kind: LimitRange
metadata:
  name: cpu-min-max-demo-lr
spec:
  limits:
    - default:
        cpu: 1
      defaultRequest:
        cpu: 0.1
      max:
        cpu: 2
      min:
        cpu: 0.1
      type: Container
